### ISSUE TITLE
Ask: what kind of world do we want

### ISSUE THREAD

**Issue by GreyArmor** [GreyArmor/SomeRogue#11]
static with randomly generated dungeons (think adom) ; or randomly generated (cataclysm dda); or randomly generated including the history of the world and stuff (dwarf fortress)

"well lets go with 2d world with some dungeons" - ok we will go with that for now

**Comment by magmabee** [comment]
I think we could try randomly generated dungeons, with a little bit of world random generation. That or we can make the world fully randomly generated. I think that the history thing from Dwarf Fortress would take a long time to implement... but we can also try. I do think it would be nice to have a randomly generated roguelike world though. I know I love the one from CDDA.

**Comment by GreyArmor** [comment]
I think of something between CDDA and DwarfFortress - 3d world but no mining, with 3d buildings, and mountains and stuff; but for now CDDA style will do;
